import sqlite3
from sqlite3 import Error

from numpy import double

conn = sqlite3.connect(database = r"/home/pi/dev/augur/data/augur.db")   

def insert_sentiments(sentiments):
    sql_create_sentiments_table = """ CREATE TABLE IF NOT EXISTS sentiments (
                                        id integer PRIMARY KEY,
                                        timestamp text NOT NULL,
                                        text_content text NOT NULL,
                                        ticker text NOT NULL,
                                        text_source text,
                                        text_sentiment_score real
                                    ); """

    """ create a table from the sql_create_sentiments_table statement
    :param conn: Connection object
    :param sql_create_sentiments_table: a CREATE TABLE statement
    :return:
    """
    try:
        c = conn.cursor()
        c.execute(sql_create_sentiments_table)
    except Error as e:
        print(e)


         

    """
        Create a new sentiment into the sentiments table
        :param conn:
          :param sentiment:
        :return: sentiment id
        """
    sql = ''' INSERT INTO sentiments(timestamp,text_content,ticker,text_source,text_sentiment_score)
                VALUES(?,?,?,?,?) '''

    cur = conn.cursor()
    cur.executemany(sql, sentiments)
    conn.commit()
    return cur.lastrowid



# def load_tweets():
#     result = []
#     tweet_keys = get_security_list()
#     for tweet_key in tweet_keys:
#         json_objects = load_data(tweet_key)
#         for jsonObj in json_objects:
#             result.append(pd.DataFrame.from_dict(json.loads(jsonObj)))
#     return result
